In [25]:
import json
import requests
import pandas as pd
import numpy as np

In [12]:
%run desktop/opentransit-metrics/mykelu/eclipses.py

In [13]:
def load_json(filename = 'routes24h20181015v2.json'):
    with open(filename, 'r') as f:
        return json.load(f)

In [14]:
test = load_json()

In [15]:
# current: refactor get_stops to allow passing in data instead of querying
def get_all_stops(data):
    bus_stops = pd.DataFrame(columns = ["VID", "DATE", "TIME", "SID", "DID", "ROUTE"])
    
    for route in [ele['rid'] for ele in test]:
        print(f"{datetime.now().strftime('%a %b %d %I:%M:%S %p')}: Starting with {route}.")
        try:
            stop_ids = [stop['id']
                for stop
                in requests.get(f"http://restbus.info/api/agencies/sf-muni/routes/{route}").json()['stops']]
                 
            route_data = [ele for ele in test if ele['rid'] == route]

            for stop_id in stop_ids:
                try:
                    stops = produce_stops(route_data, route)
                except: # TODO: figure out why requests aren't working; maybe need to feed it df with only that route data?
                    print(f"{datetime.now().strftime('%a %b %d %I:%M:%S %p')}: could not produce stops df for {stop_id} on route {route}. Skipping.")
                    break

                buses = produce_buses(route_data)

                stop = stops[stops['SID'] == stop_id].squeeze()

                try: 
                    buses = buses[buses['DID'] == stop['DID']]
                except ValueError: # accounts for stops with no associated direction
                    print(f"{datetime.now().strftime('%a %b %d %I:%M:%S %p')}: no direction associated to {stop_id} on route {route}. Skipping.")
                    continue

                eclipses = find_eclipses(buses, stop)
                nadirs = find_nadirs(eclipses)

                try:
                    nadirs["TIME"] = nadirs["TIME"].apply(lambda x: datetime.fromtimestamp(x//1000, timezone(timedelta(hours = -8))))
                    nadirs['DATE'] = nadirs['TIME'].apply(lambda x: x.date())
                    nadirs['TIME'] = nadirs['TIME'].apply(lambda x: x.time())
                    nadirs["SID"] = stop_id
                    nadirs["DID"] = stop["DID"]
                    nadirs["ROUTE"] = route
                    bus_stops = bus_stops.append(nadirs, sort = True)
                except:
                    print(f"{datetime.now().strftime('%a %b %d %I:%M:%S %p')}: could not produce stops df for {stop_id} on route {route}. Skipping.", end = "\r")              
        except KeyError:
            print(f"{datetime.now().strftime('%a %b %d %I:%M:%S %p')}: KeyError at {route}!")
            continue
                      
    if len(bus_stops) > 0:
        bus_stops['timestamp'] = bus_stops[['DATE', 'TIME']].apply(lambda x: datetime.strptime(f"{x['DATE'].isoformat()} {x['TIME'].isoformat()} -0800", 
                                                                                       "%Y-%m-%d %H:%M:%S %z"), axis = 'columns')
    
    return bus_stops

In [16]:
df = get_all_stops(test)

Sat Feb 23 04:51:05 AM: Starting with 1.
Sat Feb 23 04:54:43 AM: Starting with 3.
Sat Feb 23 04:55:18 AM: no direction associated to 6088 on route 3. Skipping.
Sat Feb 23 04:56:00 AM: Starting with 5.
Sat Feb 23 04:57:58 AM: no direction associated to 3183 on route 5. Skipping.
Sat Feb 23 04:57:59 AM: no direction associated to 3923 on route 5. Skipping.
Sat Feb 23 04:58:00 AM: no direction associated to 3200 on route 5. Skipping.
Sat Feb 23 04:58:01 AM: no direction associated to 34735 on route 5. Skipping.
Sat Feb 23 04:59:08 AM: no direction associated to 4850 on route 5. Skipping.
Sat Feb 23 04:59:09 AM: no direction associated to 7884 on route 5. Skipping.
Sat Feb 23 04:59:10 AM: no direction associated to 37563 on route 5. Skipping.
Sat Feb 23 04:59:37 AM: no direction associated to 3161 on route 5. Skipping.
Sat Feb 23 04:59:38 AM: no direction associated to 7775 on route 5. Skipping.
Sat Feb 23 04:59:38 AM: Starting with 6.
Sat Feb 23 05:01:05 AM: no direction associated to 7408 on route 6. Skipping.
Sat Feb 23 05:02:46 AM: no direction associated to 3244 on route 6. Skipping.
Sat Feb 23 05:02:46 AM: Starting with 7.
Sat Feb 23 05:05:50 AM: Starting with 8.
Sat Feb 23 05:10:03 AM: Starting with 9.
Sat Feb 23 05:13:16 AM: Starting with 10.
Sat Feb 23 05:14:47 AM: no direction associated to 5850 on route 10. Skipping.
Sat Feb 23 05:16:21 AM: no direction associated to 35850 on route 10. Skipping.
Sat Feb 23 05:16:21 AM: Starting with 12.
Sat Feb 23 05:18:24 AM: Starting with 14.
Sat Feb 23 05:19:44 AM: no direction associated to 37742 on route 14. Skipping.
Sat Feb 23 05:19:53 AM: no direction associated to 7742 on route 14. Skipping.
Sat Feb 23 05:21:20 AM: Starting with 18.
Sat Feb 23 05:23:24 AM: Starting with 19.
Sat Feb 23 05:26:32 AM: Starting with 21.
Sat Feb 23 05:28:01 AM: no direction associated to 4236 on route 21. Skipping.
Sat Feb 23 05:28:01 AM: Starting with 22.
Sat Feb 23 05:30:28 AM: Starting with 23.
Sat Feb 23 05:31:52 AM: no direction associated to 36453 on route 23. Skipping.
Sat Feb 23 05:34:07 AM: Starting with 24.
Sat Feb 23 05:35:43 AM: no direction associated to 34148 on route 24. Skipping.
Sat Feb 23 05:37:08 AM: no direction associated to 34435 on route 24. Skipping.
Sat Feb 23 05:37:09 AM: no direction associated to 14148 on route 24. Skipping.
Sat Feb 23 05:37:24 AM: Starting with 25.
Sat Feb 23 05:37:51 AM: Starting with 27.
Sat Feb 23 05:39:49 AM: Starting with 28.
Sat Feb 23 05:41:36 AM: Starting with 29.
Sat Feb 23 05:46:15 AM: Starting with 30.
Sat Feb 23 05:48:22 AM: no direction associated to 3161 on route 30. Skipping.
Sat Feb 23 05:48:22 AM: Starting with 31.
Sat Feb 23 05:50:44 AM: Starting with 33.
Sat Feb 23 05:52:28 AM: Starting with 37.
Sat Feb 23 05:54:39 AM: Starting with 38.
Sat Feb 23 05:55:51 AM: no direction associated to 35511 on route 38. Skipping.
Sat Feb 23 05:57:04 AM: Starting with 41.
Sat Feb 23 05:57:38 AM: no direction associated to 6778 on route 41. Skipping.
Sat Feb 23 05:58:19 AM: Starting with 2.
Sat Feb 23 05:58:20 AM: no direction associated to 6497 on route 2. Skipping.
Sat Feb 23 05:58:54 AM: no direction associated to 6088 on route 2. Skipping.
Sat Feb 23 05:59:11 AM: no direction associated to 6089 on route 2. Skipping.
Sat Feb 23 05:59:40 AM: no direction associated to 5658 on route 2. Skipping.
Sat Feb 23 05:59:40 AM: no direction associated to 6475 on route 2. Skipping.
Sat Feb 23 05:59:41 AM: no direction associated to 36497 on route 2. Skipping.
Sat Feb 23 05:59:58 AM: Starting with 36.
Sat Feb 23 06:02:39 AM: Starting with 35.
Sat Feb 23 06:03:54 AM: Starting with 39.
Sat Feb 23 06:04:18 AM: Starting with 43.
Sat Feb 23 06:12:30 AM: Starting with 44.
Sat Feb 23 06:18:46 AM: no direction associated to 4387 on route 44. Skipping.
Sat Feb 23 06:18:46 AM: Starting with 45.
Sat Feb 23 06:21:15 AM: Starting with 47.
Sat Feb 23 06:24:11 AM: Starting with 48.
Sat Feb 23 06:25:15 AM: no direction associated to 33462 on route 48. Skipping.
Sat Feb 23 06:26:51 AM: no direction associated to 36744 on route 48. Skipping.
Sat Feb 23 06:29:45 AM: Starting with 49.
Sat Feb 23 06:33:24 AM: Starting with 54.
Sat Feb 23 06:39:00 AM: Starting with 55.
Sat Feb 23 06:39:45 AM: Starting with 90.
Sat Feb 23 06:41:00 AM: Starting with 91.
Sat Feb 23 06:46:25 AM: Starting with J.
Sat Feb 23 06:47:38 AM: no direction associated to 4510 on route J. Skipping.
Sat Feb 23 06:48:54 AM: no direction associated to 7903 on route J. Skipping.
Sat Feb 23 06:48:55 AM: no direction associated to 4447 on route J. Skipping.
Sat Feb 23 06:48:57 AM: no direction associated to 4448 on route J. Skipping.
Sat Feb 23 06:48:58 AM: no direction associated to 37217 on route J. Skipping.
Sat Feb 23 06:48:58 AM: Starting with N.
Sat Feb 23 06:53:15 AM: no direction associated to 7405 on route N. Skipping.
Sat Feb 23 06:53:16 AM: no direction associated to 5241 on route N. Skipping.
Sat Feb 23 06:53:20 AM: no direction associated to 7903 on route N. Skipping.
Sat Feb 23 06:53:22 AM: no direction associated to 7397 on route N. Skipping.
Sat Feb 23 06:53:24 AM: no direction associated to 35241 on route N. Skipping.
Sat Feb 23 06:53:25 AM: no direction associated to 37217 on route N. Skipping.
Sat Feb 23 06:53:25 AM: Starting with PH.
Sat Feb 23 06:55:31 AM: Starting with 57.
Sat Feb 23 06:58:13 AM: Starting with 66.
Sat Feb 23 06:59:36 AM: Starting with 52.
Sat Feb 23 07:01:22 AM: Starting with 67.
Sat Feb 23 07:02:35 AM: Starting with 30X.
Sat Feb 23 07:03:42 AM: Starting with 14R.
Sat Feb 23 07:05:25 AM: Starting with 38R.
Sat Feb 23 07:08:28 AM: Starting with 82X.
Sat Feb 23 07:08:52 AM: Starting with 56.
Sat Feb 23 07:09:21 AM: no direction associated to 34575 on route 56. Skipping.
Sat Feb 23 07:09:58 AM: Starting with 88.
Sat Feb 23 07:10:14 AM: Starting with 83X.
Sat Feb 23 07:10:14 AM: KeyError at 83X!
Sat Feb 23 07:10:14 AM: Starting with 14X.
Sat Feb 23 07:11:24 AM: Starting with 81X.
Sat Feb 23 07:11:36 AM: Starting with E.
Sat Feb 23 07:11:36 AM: KeyError at E!
Sat Feb 23 07:11:36 AM: Starting with F.
Sat Feb 23 07:14:55 AM: Starting with M.
Sat Feb 23 07:15:56 AM: no direction associated to 7058 on route M. Skipping.
Sat Feb 23 07:17:59 AM: no direction associated to 37058 on route M. Skipping.
Sat Feb 23 07:18:00 AM: no direction associated to 6744 on route M. Skipping.
Sat Feb 23 07:18:01 AM: no direction associated to 7903 on route M. Skipping.
Sat Feb 23 07:18:02 AM: no direction associated to 36738 on route M. Skipping.
Sat Feb 23 07:18:04 AM: no direction associated to 37217 on route M. Skipping.
Sat Feb 23 07:18:04 AM: Starting with L.
Sat Feb 23 07:19:39 AM: no direction associated to 4510 on route L. Skipping.
Sat Feb 23 07:19:40 AM: no direction associated to 7058 on route L. Skipping.
Sat Feb 23 07:19:41 AM: no direction associated to 17058 on route L. Skipping.
Sat Feb 23 07:20:11 AM: no direction associated to 4509 on route L. Skipping.
Sat Feb 23 07:21:41 AM: no direction associated to 37058 on route L. Skipping.
Sat Feb 23 07:21:42 AM: no direction associated to 7903 on route L. Skipping.
Sat Feb 23 07:21:44 AM: no direction associated to 6738 on route L. Skipping.
Sat Feb 23 07:21:45 AM: no direction associated to 37217 on route L. Skipping.
Sat Feb 23 07:21:46 AM: no direction associated to 6744 on route L. Skipping.
Sat Feb 23 07:21:46 AM: Starting with PM.
Sat Feb 23 07:23:34 AM: Starting with NX.
Sat Feb 23 07:24:02 AM: Starting with 7X.
Sat Feb 23 07:25:34 AM: Starting with 38BX.
Sat Feb 23 07:26:14 AM: Starting with 1AX.
Sat Feb 23 07:26:53 AM: Starting with 1BX.
Sat Feb 23 07:27:25 AM: Starting with 9R.
Sat Feb 23 07:28:53 AM: no direction associated to 36575 on route 9R. Skipping.
Sat Feb 23 07:30:30 AM: Starting with C.
Sat Feb 23 07:31:51 AM: Starting with 38AX.
Sat Feb 23 07:32:33 AM: Starting with 31BX.
Sat Feb 23 07:33:15 AM: Starting with 31AX.
Sat Feb 23 07:34:00 AM: Starting with 8AX.
Sat Feb 23 07:35:18 AM: Starting with 8BX.
Sat Feb 23 07:37:43 AM: Starting with 5R.
Sat Feb 23 07:40:49 AM: no direction associated to 7775 on route 5R. Skipping.
Sat Feb 23 07:40:52 AM: no direction associated to 3161 on route 5R. Skipping.
Sat Feb 23 07:40:52 AM: Starting with 28R.

In [17]:
df.info(memory_usage = 'deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 214783 entries, 1 to 28135
Data columns (total 7 columns):
DATE         214783 non-null object
DID          214783 non-null object
ROUTE        214783 non-null object
SID          214783 non-null object
TIME         214783 non-null object
VID          214783 non-null object
timestamp    214783 non-null datetime64[ns, UTC-08:00]
dtypes: datetime64[ns, UTC-08:00](1), object(6)
memory usage: 72.3 MB

In [ ]:
unique, counts = np.unique(df.index.values, return_counts = True)
dict(zip(unique, counts))

In [31]:
df[df.index == 970]

,DATE,DID,ROUTE,SID,TIME,VID,timestamp
970,2018-10-14,9____O_N00,9,6569,23:58:15,8800,2018-10-14 23:58:15-08:00
970,2018-10-14,9____O_N00,9,6583,23:58:15,8800,2018-10-14 23:58:15-08:00
970,2018-10-14,14___I_F00,14,5693,23:31:45,7211,2018-10-14 23:31:45-08:00
970,2018-10-15,19___I_F00,19,6999,00:05:30,8422,2018-10-15 00:05:30-08:00
970,2018-10-14,24___O_F00,24,5095,23:49:15,5505,2018-10-14 23:49:15-08:00
970,2018-10-14,24___O_F00,24,5884,23:49:15,5505,2018-10-14 23:49:15-08:00
970,2018-10-15,36___O_F00,36,6228,18:20:53,8523,2018-10-15 18:20:53-08:00
970,2018-10-15,44___O_F00,44,3694,00:08:00,8840,2018-10-15 00:08:00-08:00
970,2018-10-15,55___I_F00,55,3291,05:57:53,8869,2018-10-15 05:57:53-08:00
970,2018-10-15,55___I_F00,55,33293,05:57:53,8869,2018-10-15 05:57:53-08:00
970,2018-10-15,91___I_N00,91,5792,00:03:15,8617,2018-10-15 00:03:15-08:00
970,2018-10-15,91___I_N00,91,3377,00:03:15,8617,2018-10-15 00:03:15-08:00
970,2018-10-15,91___I_N00,91,3354,00:03:15,8617,2018-10-15 00:03:15-08:00
970,2018-10-15,91___I_N00,91,7448,00:03:15,8617,2018-10-15 00:03:15-08:00
970,2018-10-15,PH___O_F00,PH,5156,05:42:22,24,2018-10-15 05:42:22-08:00
970,2018-10-15,PH___O_F00,PH,5164,05:42:22,24,2018-10-15 05:42:22-08:00
970,2018-10-15,66___I_F00,66,4861,06:12:53,8519,2018-10-15 06:12:53-08:00
970,2018-10-15,66___I_F00,66,4859,06:12:53,8519,2018-10-15 06:12:53-08:00

In [33]:
with open('routes20181015v2stops.json', 'w') as f:
    df.reset_index().to_json(f)